//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeraPlayerExp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Experience : global::System.Configuration.ApplicationSettingsBase {
        
        private static Experience defaultInstance = ((Experience)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Experience())));
        
        public static Experience Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>62</string>\r\n  <string>840</string>\r\n  <string>1846</string>\r\n  <string>30" +
            "48</string>\r\n  <string>4470</string>\r\n  <string>6145</string>\r\n  <string>8113</s" +
            "tring>\r\n  <string>10410</string>\r\n  <string>13088</string>\r\n  <string>16197</str" +
            "ing>\r\n  <string>19795</string>\r\n  <string>23952</string>\r\n  <string>29940</strin" +
            "g>\r\n  <string>35820</string>\r\n  <string>43748</string>\r\n  <string>52633</string>" +
            "\r\n  <string>62859</string>\r\n  <string>78574</string>\r\n  <string>98077</string>\r\n" +
            "  <string>114490</string>\r\n  <string>143113</string>\r\n  <string>178891</string>\r" +
            "\n  <string>223614</string>\r\n  <string>275045</string>\r\n  <string>355555</string>" +
            "\r\n  <string>419444</string>\r\n  <string>514305</string>\r\n  <string>684342</string" +
            ">\r\n  <string>747584</string>\r\n  <string>839475</string>\r\n  <string>954831</strin" +
            "g>\r\n  <string>1122643</string>\r\n  <string>1254159</string>\r\n  <string>1454823</s" +
            "tring>\r\n  <string>1719869</string>\r\n  <string>2094194</string>\r\n  <string>259295" +
            "6</string>\r\n  <string>3029644</string>\r\n  <string>3423497</string>\r\n  <string>38" +
            "68552</string>\r\n  <string>4448835</string>\r\n  <string>5427578</string>\r\n  <strin" +
            "g>7452245</string>\r\n  <string>9542027</string>\r\n  <string>10942319</string>\r\n  <" +
            "string>12815896</string>\r\n  <string>14351495</string>\r\n  <string>17700998</strin" +
            "g>\r\n  <string>20002128</string>\r\n  <string>22002128</string>\r\n  <string>24950654" +
            "</string>\r\n  <string>27707107</string>\r\n  <string>30765345</string>\r\n  <string>3" +
            "4158159</string>\r\n  <string>37921882</string>\r\n  <string>42096768</string>\r\n  <s" +
            "tring>46727412</string>\r\n  <string>51863218</string>\r\n  <string>106333740</strin" +
            "g>\r\n  <string>171558828</string>\r\n  <string>240545856</string>\r\n  <string>320254" +
            "565</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PlayerExp {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PlayerExp"]));
            }
            set {
                this["PlayerExp"] = value;
            }
        }
    }
}
